CREATE TABLE CUSTOMER (
IdCustomer INT NOT NULL PRIMARY KEY,
SURNAME CHAR(10),
FIRSTNAME CHAR(10),
PHONE NUMERIC(20),
CITY CHAR(50),
STREET CHAR(250),
BUILDINGNO NUMERIC(10),
FLATNO NUMERIC(10)
);

CREATE TABLE PIZZA(
IdPizza INT NOT NULL PRIMARY KEY,
PIZZANAME CHAR(250)
);

INSERT INTO CUSTOMER VALUES
(1, 'WHITE', 'MARK', '7972218389', 'Warszawa', 'Al. Krakowskie', '42', '32');

INSERT INTO PIZZA VALUES(
1, 'MARGARITTA');

INSERT INTO PIZZA VALUES(
2, 'KEBAB');